---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: lxd

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: OSCam-Ubuntu1604
    source:
      alias: ubuntu/xenial/amd64

  - name: OSCam-Ubuntu1404
    source:
      alias: ubuntu/trusty/amd64

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

scenario:
  name: default
